// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://chjlurgjgdgpfzseuozx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNoamx1cmdqZ2RncGZ6c2V1b3p4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU5OTQyNDIsImV4cCI6MjA1MTU3MDI0Mn0.u0bvM2yKqAFUnhHXuI9ZSNj1EHizWNLiRmD17887g1c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);